AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'FIAP: Exame final disciplina AWS Serverless Architecture, com professor Peterson de Oliveira Larentis'

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME: !Ref TripTable
        ENDPOINT_OVERRIDE: ""

Resources:

  TripTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip_mgnt
      AttributeDefinitions:
        - AttributeName: partition
          AttributeType: S
        - AttributeName: uuid
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: country
          AttributeType: S
      KeySchema:
        - AttributeName: partition
          KeyType: HASH
        - AttributeName: uuid
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: dateLSI
          KeySchema:
            - AttributeName: partition
              KeyType: HASH
            - AttributeName: date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: countryLSI
          KeySchema:
            - AttributeName: partition
              KeyType: HASH
            - AttributeName: country
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  CreateATripRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/aws.serverless.arch-1.0-SNAPSHOT-jar-with-dependencies.jar
      Handler: fiap.aws.serverless.arch.trip.domain.TripController$CreateATripRecordFunction::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TripTable
      Events:
        CreateATripRecord:
          Type: Api
          Properties:
            Path: /trips
            Method: post

  GetTripRecordsByPeriodFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/aws.serverless.arch-1.0-SNAPSHOT-jar-with-dependencies.jar
      Handler: fiap.aws.serverless.arch.trip.domain.TripController$GetTripRecordsByPeriodFunction::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TripTable
      Events:
        GetTripRecordsByPeriod:
          Type: Api
          Properties:
            Path: /trips
            Method: get
            RequestParameters:
              - method.request.querystring.start
              - method.request.querystring.end

  GetTripRecordsByCountryAndCityLikelyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/aws.serverless.arch-1.0-SNAPSHOT-jar-with-dependencies.jar
      Handler: fiap.aws.serverless.arch.trip.domain.TripController$GetTripRecordsByCountryAndCityLikelyFunction::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TripTable
      Events:
        GetTripRecordsByCountryAndCityLikely:
          Type: Api
          Properties:
            Path: /trips/{country}
            Method: get
            RequestParameters:
              - method.request.querystring.city

Outputs:

  CreateATripRecordFunction:
    Description: "CreateATripRecordFunction Lambda Function ARN"
    Value: !GetAtt CreateATripRecordFunction.Arn

  GetTripRecordsByPeriodFunction:
    Description: "GetTripRecordsByPeriodFunction Lambda Function ARN"
    Value: !GetAtt GetTripRecordsByPeriodFunction.Arn

  GetTripRecordsByCountryAndCityLikelyFunction:
    Description: "GetTripRecordsByCountryAndCityLikelyFunction Lambda Function ARN"
    Value: !GetAtt GetTripRecordsByCountryAndCityLikelyFunction.Arn